import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app for Maya Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" max-w-7xl mx-auto">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
